# Generated by Django 6.0.6 on 2026-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idempotencyrecord',
            old_name='request_body',
            new_name='response_body',
        ),
    ]
