# Generated by Django 6.0.6 on 2026-06-21 12:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_request_body_idempotencyrecord_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_expires_at),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='response_body',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='response_status',
            field=models.IntegerField(default=0),
        ),
    ]
